# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0002_auto_20180325_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='desc_text',
        ),
        migrations.RemoveField(
            model_name='description',
            name='id',
        ),
        migrations.AddField(
            model_name='description',
            name='course',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Course_app.Course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='description',
            name='desc_text',
            field=models.CharField(default='', max_length=255),
        ),
    ]
